[package]
name = "raytracer"
version = "0.1.0"
authors = ["Paul Cacheux <paulcacheux@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
rand_distr = "0.2"
noise = "0.6"
image = "0.23"
nalgebra = "0.21"
